#!/bin/bash

FILE="$1"
PARSE_LOG="parse.log"
INFER_LOG="infer.log"
FAIAL_LOG="faial.log"
shift

# Setup temporary file
TMP1=$(tempfile)
TMP2=$(tempfile)
TMP3=$(tempfile)

cleanup(){
  rm -f "${TMP2}" "${TMP1}" "${TMP3}";
}

trap "{ cleanup; }" EXIT

if ! cu-to-json "$FILE" --extra-arg=-ferror-limit=1 > "${TMP1}" 2> "${TMP2}"
then
  >&2 echo "ERROR: cu-to-json $FILE"
  echo "-------------------------------------------------------------------" >> "${PARSE_LOG}";
  cat "${TMP2}" >> "$PARSE_LOG"
  cleanup
  exit 1
fi

if ! faial-infer "${TMP1}" -t json > "${TMP2}" 2> "${TMP3}"; then
  >&2 echo "ERROR: faial-infer $FILE"
  echo "-------------------------------------------------------------------" >> "${INFER_LOG}";
  echo "ERROR: $FILE" >> "${INFER_LOG}";
  cat "${TMP3}" >> "${INFER_LOG}";
  cleanup;
  exit 2
fi

if ! main --json "${TMP2}" $(faial-gv "$FILE") > "${TMP1}"; then
  >&2 echo "ERROR: faial $FILE"
  echo "-------------------------------------------------------------------" >> "${FAIAL_LOG}";
  echo "ERROR: $FILE" >> "${FAIAL_LOG}";
  cat "${TMP1}" >> "${FAIAL_LOG}";
  cleanup
  exit 3
fi

cleanup