#!/bin/bash

trap "exit 255" SIGINT SIGTERM

PARSE_LOG="parse.log"
INFER_LOG="infer.log"
FAIAL_LOG="faial.log"

if [ -f "${PARSE_LOG}" ]; then
  >&2 echo -e "Remove log file first:\n\n\trm -f '${PARSE_LOG}'\n"
  exit 1
fi
if [ -f "${INFER_LOG}" ]; then
  >&2 echo -e "Remove log file first:\n\n\trm -f '${INFER_LOG}'\n"
  exit 1
fi
if [ -f  "${FAIAL_LOG}" ]; then
  >&2 echo -e "Remove log file first:\n\n\trm -f '${FAIAL_LOG}'\n"
  exit 1
fi

while read fname
do
  case "${fname}" in
    *.cu)
      faial-bench "${fname}" \
        && echo "OK: ${fname}"
      ;;
    *)
      >&2 echo "SKIP: ${fname}"
      ;;
  esac
done < "$1"
exit 0

