version: "3.8"
services:
    base:
        build:
            dockerfile: docker/base.Dockerfile
            context: ..
        image: registry.gitlab.com/umb-svl/faial/faial:base

    user:
        build:
            dockerfile: docker/user.Dockerfile
            context: ..

    ci:
        build:
            dockerfile: docker/ci.Dockerfile
            context: ..
        image: registry.gitlab.com/umb-svl/faial/faial:ci

    dev:
        build:
            dockerfile: docker/dev.Dockerfile
            context: ..

    debug-ci:
        build:
            dockerfile: docker/debug-ci.Dockerfile
            context: ..
